test: skip the source bundle on exact tag
When building for the release, as the release hasn't been finalized yet,
the test might fail.

```
    run.go:146: Running "/home/runner/_work/talos/talos/_out/talosctl-linux-amd64 --talosconfig /tmp/e2e/docker/talosconfig image talos-bundle v1.13.0-alpha.0"
    run.go:210:
        	Error Trace:	/src/internal/integration/base/run.go:210
        	            				/src/internal/integration/base/cli.go:107
        	            				/src/internal/integration/cli/image.go:142
        	            				/go/src/runtime/asm_amd64.s:1693
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestIntegration/cli.ImageSuite/TestSourceBundle
        	Messages:   	command failed, stdout: "", stderr: "error fetching official extensions for v1.13.0-alpha.0: HEAD https://ghcr.io/v2/ghcr.io/siderolabs/extensions/manifests/v1.13.0-alpha.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)\n"
```

Signed-off-by: Andrey Smirnov <andrey.smirnov@siderolabs.com>
(cherry picked from commit f0d8a685173354e5fd148786872062a342c4282a)