test: fix a flake in the manifest sync test
A sample failure:

```
manifests.go:133:
        	Error Trace:	/src/internal/integration/k8s/manifests.go:133
        	Error:      	[]string{"/usr/local/bin/kube-proxy", "--cluster-cidr=10.244.0.0/16", "--conntrack-max-per-core=0", "--hostname-override=$(NODE_NAME)", "--kubeconfig=/etc/kubernetes/kubeconfig", "--proxy-mode=nftables"} does not contain "--nodeport-addresses=0.0.0.0/0"
        	Test:       	TestIntegration/k8s.ManifestsSuite/TestSync
    manifests.go:137: disabling kube-proxy
```

My running theory is that `List()` picks up a stale pod, so trying to
filter it out and log it in full if we hit it.

Signed-off-by: Andrey Smirnov <andrey.smirnov@siderolabs.com>
(cherry picked from commit 9b9542cc55ee6d08f3490d270c1b497c7b9d3049)